### ISSUE TITLE
dokerization

### ISSUE THREAD

**Issue by ristes** [petarzafirovski/TaskPlanning#1]
- dockerbuild
- docker-compose
- redeploy.sh

**Comment by SaraMisajlovska** [comment]
We created the docker-compose and pushed the changes to the repo, but we aren't sure if we should also create a dockerfile or if that is something you will do when deploying the app on a server. Please let us know if something needs to be changed/added.

**Comment by ristes** [comment]
redeploy.sh
```sh
#docker ps | grep food-base-web | awk '{print $1}' | xargs docker stop
docker-compose down
docker image rm -f food-base-web_food-base-web

git pull

if [ $1 = 'react' ]
then
	echo 'compile react app'
	#compile react app
	cd static/ner
	npm install
	npm run-script build
	rm -rf node_modules
	cd ../../
fi

#docker build -t food-base-web:latest .
#docker run -d -p 5000:5000 food-base-web
docker-compose  up -d
echo "Docker id: "
docker ps | grep food-base-web | awk '{print $1}'
echo "Logs: "
docker ps | grep food-base-web | awk '{print $1}' | xargs docker logs -f
```

**Comment by ristes** [comment]
Dockerfile

```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} project-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "/project-0.0.1-SNAPSHOT.jar"]
```

**Comment by ristes** [comment]
docker-compose.yml

```yml
version: "3.3"
services:
  project_db:
    image: postgres:10.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    container_name: project_db
  project_backend:
    depends_on:
      - project_db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_backend
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://project_db:5432/project"
      - "ELASTICSEARCH_URL=http://project_es:9200"
volumes:
  db-data:
```
